Website = "https://github.com/jc-design/rp_mgmt"

[Details]
  Icon = "Icon.png"
  Name = "rp_mgmt"
  ID = "de.jc-design.rp_mgmt"
  Version = "1.0.0"
  Build = 5

[LinuxAndBSD]
  GenericName = "rp_mgmt"
  Comment = "manage your rpg characters"
